---
title: "Hospital Star Rating Tutotial Using True LVM Model"
author: "Ren-Huai Huang, Ascension Health Care Excellence Analytics & ACRI"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# Install the packages before loading if you didn't do so. 
# require(devtools); 
# devtools::install_github("huangrh/rstarating");
# devtools::install_github("huangrh/relvm");
# devtools::install_github("huangrh/rclus");
require(rstarating); require(relvm); require(rclus)
```

```{r oct2016_set}

set.seed(100)
# Load the input dataset from October 2016. 
x       <- cms2016oct_input

# Data preparation. 
object  <-  x <- mstbl(x)

# LVM model fitting. 
# fitx       <-   relvm(x)

fitx       <-   relvm_noad(x)  # noad <== quad
# K-means clustering.

sr <- rating(fitx$groups$summary_score,method = "rclus", score_col="sum_score_win",iter.max = 1)

# Save your data. 
op <- out_dir("C:/rhuang/github/rstarating/inst")
write.csv(sr$summary_score, file=file.path(op,"Oct2016_sum_score_truelvm_fit2.csv"))
write.csv(fitx$groups$pars, file=file.path(op,"Oct2016_par_truelvm_fit2.csv"))
write.csv(fitx$groups$preds, file=file.path(op,"Oct2016_preds_truelvm_fit2.csv"))

# Compare
cms_oct16 <- read.csv(
    file.path(
        "T:/Clinical Excellence/Analytics/Data Sources/cmsData/2016/20161110/Hospital_Revised_FlatFiles_20161110",
        "Hospital General Information.csv"),
    na.strings = "Not Available",
    stringsAsFactors = F) %>% 
    select('Provider.ID', "Hospital.overall.rating") %>% 
    rename(ccnid = 'Provider.ID', cms_star="Hospital.overall.rating") %>% 
    merge(y = sr$star,by="ccnid",all=T)
    
```


```{r dec2016}
# Load the input data
x3    <- read.csv(system.file("/cms/dec2016/sas_input_2016dec.csv",package="cmsdata"))
x3    <- mstbl(x3)
fitx3 <- relvm(x3)
sr3   <- rating(fitx3$groups$summary_score,iter.max = 110) 

# Save your data. Change the output directory accordingly. 
op <- out_dir("C:/rhuang/github/rstarating/inst")
write.csv(sr3$summary_score, file=file.path(op,"Dec2016_sum_score_truelvm_fit3.csv"))
write.csv(fitx3$groups$pars, file=file.path(op,"Dec2016_par_truelvm_fit3.csv"))
write.csv(fitx3$groups$preds, file=file.path(op,"Dec2016_preds_truelvm_fit3.csv"))

```
