---
title: "Random Effect Latent Variable Model"
author: "Ren-Huai Huang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<style type="text/css"> h1 {font-size:18px;} </style>

```{r data, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,fig.height = 6,fig.width = 8)
require(rstarating)
require(relvm)
library(plotly)

group <- "outcome_safty"
x <- object <- mstbl(cms2016oct_input)
subdat    <- subgroup(x)
score <- score_tbl <- mstbl_std <- as.matrix(subdat[[group]]$mstbl_std)
wts <- wts_tbl     <- as.matrix(subdat[[group]]$wtbl)

# Setup and initialize the parameters
nc <- ncol(mstbl_std);

par <- init <- unlist(list(mu  = rep(0, nc),fl  = rep(1, nc),err = rep(1, nc)))

qpoints= 30
cc <- pracma::gaussHermite(qpoints);
fv  <- 1.4142135623730951 * cc$x
logccw <- log(cc$w)
dnorm2 <- function(x,mean=0,sd=1) {-(log(2 * pi) +2*log(sd)+((x-mean)/sd)^2)/2}


set.seed(100)
fitx <- readRDS(file.path("C:/rhuang/workspace/R/hospitalrating/inst/2016oct/r","fitx_qpts30_oct2016.rds"))
par <- init <- unlist(list(mu=fitx[[group]]$par$mu,
                           fl=fitx[[group]]$par$fl,
                           err=fitx[[group]]$par$err))
```

#### negLogLikFun-16  
```{r v16, echo = FALSE}
set.seed(100)

# speedup Vectorized Estimation function
venll16 <- function(par,score,wts,qpoints) {
    cc <- pracma::gaussHermite(qpoints);
    # Reconstruction of the parameters
    nr <- nrow(score); nc <- ncol(score)
    mu    <- par[grepl("mu", names(par))]         #
    fl    <- par[grepl("fl", names(par))]         # factor loading
    err   <- par[grepl("err", names(par))]
    
    # 2nd derivative: coefs <- sqrt(2/(rowSums((fl^2 * wts/err^2), na.rm = TRUE) + 1))
    coefs <- rep(sqrt(2),nr)
    
    # fv matrix
    fv_mtx  <- cc$x %o% coefs

    # 3D array: 
    # wts_arr   <- aperm(array(wts,  dim=c(nr,nc,qpoints)),c(2,3,1))
    # score_arr <- aperm(array(score,dim=c(nr,nc,qpoints)),c(2,3,1))
    # means_arr <- array(mu,         dim=c(nc,qpoints,nr)) + fl %o% fv_mtx
    
    # Weighted log likelyhood /# Joint probability in log scale.
    wll_mtx   <- colSums(wts_arr * dnorm2(score_arr, mean=means_arr, sd = err),na.rm=TRUE)
    joint_mtx <- wll_mtx +  dnorm_cpp(fv_mtx, mean=0,sd=1)
    
    fn <- function(x) {
        exp(sum(w * dnorm2(s, mean=mu+fl*x, sd = err),na.rm=TRUE)+dnorm_cpp(x, mean=0,sd=1))
    }
    
    fn <- function(x) exp(dnorm(x,log=TRUE))
    
    # Gaussian quadrature integral approximation
    gqi <- matrixStats::colLogSumExps(joint_mtx + log(cc$w) +(cc$x)^2,na.rm=TRUE)
    #         gqio <- log(colSums(exp(joint_mtx + log(cc$w) +(cc$x)^2)))
    # 
    #gqio<-log(colSums(exp( wll_mtx+log(cc$w)+ dnorm_cpp(fv_mtx,mean=0,sd=1)+(cc$x)^2),na.rm=TRUE))
     gqio<-log(colSums(exp( wll_mtx+log(cc$w)+ log(1/sqrt(2*pi))),                     na.rm=TRUE))
    sum(abs(gqio-gqi))
    

    if (FALSE) {
        final2 <- log(coefs*colSums(exp( wll_mtx+log(cc$w)+ log(1/sqrt(2*pi)))))
        sum(final2)
    }
    
    -sum(log(coefs)+gqi, na.rm=TRUE)
}
venll16(par=init,score=as.matrix(subdat[[group]]$mstbl_std), 
        wts=as.matrix(subdat[[group]]$wtbl),qpoints) - 22053.166744270311 #use final parameters. 
```





#### negLogLikFun-15  
```{r v15, echo = FALSE}
set.seed(100)

# speedup Vectorized Estimation function
venll15 <- function(par,score,wts,qpoints) {
    cc <- pracma::gaussHermite(qpoints);
    # Reconstruction of the parameters
    nr <- nrow(score); nc <- ncol(score)
    mu    <- par[grepl("mu", names(par))]         #
    fl    <- par[grepl("fl", names(par))]         # factor loading
    err   <- par[grepl("err", names(par))]
    
    # 2nd derivative
    # coefs <- sqrt(2/(rowSums((fl^2 * wts/err^2), na.rm = TRUE) + 1))
    coefs <- rep(sqrt(2),nr)
    
    # fv matrix
    fv_mtx  <- cc$x %o% coefs

    # 3D array: 
    wts_arr   <- aperm(array(wts,  dim=c(nr,nc,qpoints)),c(2,3,1))
    score_arr <- aperm(array(score,dim=c(nr,nc,qpoints)),c(2,3,1))
    means_arr <- array(mu,         dim=c(nc,qpoints,nr)) + fl %o% fv_mtx
    
    # Weighted log likelyhood /# Joint probability in log scale.
    wll_mtx   <- colSums(wts_arr * dnorm2(score_arr, mean=means_arr, sd = err),na.rm=TRUE)
    joint_mtx <- wll_mtx +  dnorm_cpp(fv_mtx, mean=0,sd=1)
    
    # Gaussian quadrature integral approximation
    gqi <- matrixStats::colLogSumExps(joint_mtx + log(cc$w) +(cc$x)^2,na.rm=TRUE)
    #         gqio <- log(colSums(exp(joint_mtx + log(cc$w) +(cc$x)^2)))
    # 
    #gqio<-log(colSums(exp( wll_mtx+log(cc$w)+ dnorm_cpp(fv_mtx,mean=0,sd=1)+(cc$x)^2),na.rm=TRUE))
     gqio<-log(colSums(exp( wll_mtx+log(cc$w)+ log(1/sqrt(2*pi))),                     na.rm=TRUE))
    max(gqio-gqi)
    

    if (FALSE) {
        dev.off();par(mar=rep(2,4));layout(matrix(1:3,3));
        plot(cc$x,cc$w)
        plot(cc$x,exp(wll_mtx[,which.max(wll_mtx[1,])]));abline(v=cc$x)
        plot(cc$x,cc$w*exp(wll_mtx[,which.max(wll_mtx[1,])]),ylim=c(0,1));abline(v=cc$x)
        
        # 
        final2 <- log(coefs*colSums(exp( wll_mtx+log(cc$w)+ log(1/sqrt(2*pi)))))
        sum(final2)
    }
    
    -sum(log(coefs)+gqi, na.rm=TRUE)
}
venll15(par=init,score=as.matrix(subdat[[group]]$mstbl_std), 
        wts=as.matrix(subdat[[group]]$wtbl),qpoints) - 22053.166744270311 #use final parameters. 
```





## Set the parameters as initials. 
```{r}
groups <- names(subdat);n = 1200;

out1 <- sapply(groups, function(group){
    
    mstbl_std <- as.matrix(subdat[[group]]$mstbl_std)
    wts=as.matrix(subdat[[group]]$wtbl)
    nc <- ncol(mstbl_std);
    par <- init <- unlist(list(mu  = rep(0, nc),fl = rep(1, nc),err = rep(1, nc)))
    
    sumNegLogLik<- sapply(5:(4+n), function(qpt) venll15(par=init, score=mstbl_std, wts=wts,qpt))
    sumNegLogLik
},simplify = FALSE)

#----------------------------------------
# print
out <- sapply(groups,function(group){
    x=out1[[group]]; diff = x[2:n]-x[1:(n-1)]
    cat(group,": differences"); print(diff); cat(rep("-",65),"\n",sep="")
},simplify = FALSE)

# 
htmltools::tagList(sapply(groups,function(group){    
    x=out1[[group]]; diff = x[2:n]-x[1:(n-1)]
    #
    plot_ly(x0=1,dx=1,y=x,type="scatter",mode="markers") %>%
        layout(title=paste("SumNegLogLik:",group,"with initial parameters"), 
               yaxis = list(title="SumNegLogLik"))},simplify = FALSE))

#  
htmltools::tagList(sapply(groups,function(group){
    x=out1[[group]];diff = x[2:n]-x[1:(n-1)]
    # 
    plot_ly(x0=1,dx=1,y=diff,type="scatter",mode="markers") %>%
        layout(title=paste("SumNegLogLik Differences:",group,"with initial parameters"), 
               yaxis = list(title="Difference"))},simplify = FALSE))
```

## Set the parameters as fitted. 
```{r}

out2 <- sapply(groups, function(group){
    
    mstbl_std <- as.matrix(subdat[[group]]$mstbl_std)
    wts=as.matrix(subdat[[group]]$wtbl)
    init <- unlist(list(mu=fitx[[group]]$par$mu,fl=fitx[[group]]$par$fl,err=fitx[[group]]$par$err))
    
   (sumNegLogLik<- sapply(5:(4+n), function(qpt) venll15(par=init, score=mstbl_std, wts=wts,qpt)))
}, simplify = FALSE) 

# ------------------------------------
# print
out <- sapply(groups,function(group){
    x=out2[[group]]; diff = x[2:n]-x[1:(n-1)]
    cat(group,": differences"); print(diff); cat(rep("-",65),"\n",sep="")
},simplify = FALSE)

# plot_ly
htmltools::tagList(sapply(groups,function(group){
    x=out2[[group]]
    diff = x[2:n]-x[1:(n-1)]
    # 
    p<-plot_ly(x0=1,dx=1,y=x,type="scatter",mode="markers") %>%
        layout(title=paste("SumNegLogLik:",group, "with fitted parameters"), 
               yaxis = list(title="SumNegLogLik"))},simplify = FALSE))
# plot_ly
htmltools::tagList(sapply(groups,function(group){
    x=out2[[group]]
    diff = x[2:n]-x[1:(n-1)]
    
    plot_ly(x0=1,dx=1,y=diff,type="scatter",mode="markers") %>%
        layout(title=paste("SumNegLogLik Differences:",group,"with fitted parameters"), 
               yaxis = list(title="Difference"))},simplify = FALSE))
```





