---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}

require(cmsdata);require(rstarating);require(relvm); require(rclus);require(dplyr)
# fitted 
files <- list_files("C:/rhuang/workspace/R/starsumm/vignettes/update2018Jan/output",
                    patterns = "fit_dat2017.*rds$",recursive = F)
fits  <- sapply(files, readRDS,simplify = FALSE)
names(fits) <- gsub("\\.rds|fit_dat", "", basename(names(fits)))
names(fits) <- substr(names(fits),1,nchar(names(fits))-13)
str(fits,1)

# Star Input File
path = "T:/Clinical Excellence/Analytics/Data Sources/cmsData/star_rating_input_file"
file = file.path(path,"all_data_2017dec.csv")
dat <- read.csv(file, stringsAsFactors = F) %>% colnames_tolower()


# Hospital General Information   
path = "T:/Clinical Excellence/Analytics/Data Sources/cmsData/2017/20171221/Hospital_Revised_Flatfiles20171221"
file = file.path(path,"Hospital General Information.csv")
info  <- read.csv(file,stringsAsFactors = FALSE, na.strings=c("Not Available")) %>% 
    colnames_tolower() %>% 
    colnames_wiper(pattern="\\.",with="_") %>%
    subset(select=c("provider_id","hospital_overall_rating")) %>%
    rename(ccnid=provider_id)

#
asc <- ascdata::asc_facility()
```

```{r}
fit_noad <- fits$`2017dec_non_adaptive_30qpts`
pars <- fit_noad$groups$pars

# Object
object <- x <- mstbl(dat)
groups=NULL
fit_pars=list(qpoints=15,
         init=pars,
         predict=TRUE,
         adaptive=c("ad","noad"))

# 


```

```{r}

file <- file.path("C:/rhuang/workspace/R/starsumm/vignettes/update2018Jan/output",
                  paste0("fit_dat2017dec_noad30_ad15_",Sys.Date(),".rds"))
if (file.exists(file)) {
    fit <- readRDS(file)
} else {
    fit <- relvm_adaptive2(x,fit=fit_pars)
    saveRDS(fit,file=file)
}
```

```{r}
# sum score
ss <- fit$groups$summary_score
ss$group <- cut(ss$sum_score,breaks=c(quantile(ss$sum_score,probs=seq(0,1,0.2))),
                labels=paste0(seq(0,80,20),"-",seq(20,100,20)),include.lowest = TRUE)

cl  <- rclus(ss$sum_score,seeds=tapply(ss$sum_score,ss$group,median),maxiter = 5000,strict = NULL)
cl2 <- rclus(ss$sum_score,seeds=cl$centers,maxiter=5000, strict =1)
star = data.frame(ccnid=ss$ccnid,star=cl2$star,stringsAsFactors = F) %>%
    merge(y=info,by="ccnid",all=TRUE)
asc_star <- star[star$ccnid %in% asc$ccnid,]

asc_star %>% subset(star != hospital_overall_rating)
```




