---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include=F}
require(rstarating);require(relvm)
```

### Test the data transformation 

```{r}
x17 <- cms_star_rating_input_2017dec

# 

measures <- paste0("hai_",1:6)
for (measure in measures) {
     object[,measure] <- ifelse(object[,measure] == 0,NA,object[,measure])
     object[,paste0(measure,"_den")] <- ifelse(is.na(object[,measure]),NA,
                                                object[,paste0(measure,"_den")])
}

# 
mtl <- create_measure_tbl(cms_star_rating_input_2017dec)
par(mfrow=c(2,3))
for (measure in paste0("hai_",1:6)) {
    x17[,measure] <- log(x17[,measure]+ 1e-5)
    hist(x17[,measure],breaks=100,main=measure)
}

x17 <- mstbl(x17)
fit <- relvm(x17,group="outcome_safty")
fit$groups

```



```{r}
object <- mstbl(cms_star_rating_input_2017dec)
mtl     <- create_measure_tbl(x$mstbl_std)
safty    <- mtl[mtl$group %in% "outcome_safty","name"]
object$mstbl_std <- object$mstbl_std[c("ccnid",safty)]

for (measure in c("comp_hip_knee","psi_90_safety")) {
    object$mstbl_std[measure] = NULL
}

# weight
wtl <- create_measure_tbl(x$wtbl)
w_safty    <- wtl[wtl$group %in% "outcome_safty","name"]
object$wtbl<- object$wtbl[c("ccnid",w_safty)]

fit3 <- relvm(object,group="outcome_safty")
fit3$groups
```


### Exclude "psi_90_safety" & "comp_hip_knee" & Exclude hospitals with SIR == 0
```{r}
object  <- cms_star_rating_input_2017dec


# remove 0 from sir
measures <- paste0("hai_",1:6)
for (measure in measures) {
     object[,measure] <- ifelse(object[,measure] == 0,NA,object[,measure])
     object[,paste0(measure,"_den")] <- ifelse(is.na(object[,measure]),NA,
                                                object[,paste0(measure,"_den")])
}

# log scale 
par(mfrow=c(2,3),mar=c(2,1,1,1))
for (measure in paste0("hai_",1:6)) {
    object[,measure] <- log(object[,measure])
    hist(object[,measure],breaks=100,main=measure)
}

object <- mstbl(object)

# keep only the hai
mtl     <- create_measure_tbl(object$mstbl_std)
safty   <- mtl[mtl$group %in% "outcome_safty","name"]
object$mstbl_std <- object$mstbl_std[c("ccnid",safty)]
for (measure in c("comp_hip_knee","psi_90_safety")) {
    object$mstbl_std[measure] = NULL
}

# weight
wtl <- create_measure_tbl(object$wtbl)
w_safty    <- wtl[wtl$group %in% "outcome_safty","name"]
object$wtbl<- object$wtbl[c("ccnid",w_safty)]
for (measure in c("comp_hip_knee_wt","psi_90_safety_wt")) {
    object$wtbl[measure] = NULL
}

# 
for (measure in paste0("hai_",1:6)) {
    object$mstbl_std[,measure] <- ifelse(is.na(object$mstbl_std[,measure]),NA, rnorm(4579))
}

# 
for (wt in paste0("hai_",1:6,"_wt")) {
    object$wtbl[,wt] <- ifelse(is.na(object$wtbl[,wt]), NA, 1)
}


fit3 <- relvm(object,group="outcome_safty")
fit3$groups
```


### Exclude "psi_90_safety" & "comp_hip_knee" & Exclude hospitals with SIR == 0
```{r}
object  <- cms_star_rating_input_2017dec
mtl      <- create_measure_tbl(object)

# Exclude the sir=0
measures <- paste0("hai_",1:6)
for (measure in measures) {
     object[,measure] <- ifelse(object[,measure] == 0,NA,object[,measure])
     object[,paste0(measure,"_den")] <- ifelse(is.na(object[,measure]),NA,
                                                object[,paste0(measure,"_den")])
}

# log scale 
par(mfrow=c(2,3))
for (measure in paste0("hai_",1:5)) {
    object[,measure] <- log(object[,measure])
    skew <- e1071::skewness(object[,measure],na.rm=TRUE) %>% round(2)
    
    hist(object[,measure],breaks=100,main=paste(measure,"skew=",skew))
}

object <- mstbl(object)


mtl     <- create_measure_tbl(object$mstbl_std)
safty   <- mtl[mtl$group %in% "outcome_safty","name"]
object$mstbl_std <- object$mstbl_std[c("ccnid",safty)]


# weight
wtl <- create_measure_tbl(object$wtbl)
w_safty    <- wtl[wtl$group %in% "outcome_safty","name"]
object$wtbl<- object$wtbl[c("ccnid",w_safty)]


fit3 <- relvm(object,group="outcome_safty")
fit3$groups
```



```{r}
par(mfrow=c(2,3),mar=c(2,1,1,1))
for (wt in paste0("hai_",1:6,"_wt")) {
    hist(object$wtbl[,wt],breaks=10, main=wt)
}
```

```{r}
for (m in paste0("hai_",1:6)) {
    hist(object$mstbl_std[,m],breaks=100,main=m)
}
```


