# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp Log Density
#'
#' Log density fuction
#'
#' @export
dnorm_cpp <- function(x, mean = 0, sd = 1) {
    .Call('relvm_dnorm_cpp', PACKAGE = 'relvm', x, mean, sd)
}

#' Array
#'
#' Array in rcpp
#'
#' @export
arrayC <- function(input, dim) {
    .Call('relvm_arrayC', PACKAGE = 'relvm', input, dim)
}

#' Prediction negLogLik Function
#'
#' Prediction negLogLik Function used in in pred function in pred.R
#'
#' @export
pnll_cpp <- function(fv, score_row, wts_row, err, mu, fl) {
    .Call('relvm_pnll_cpp', PACKAGE = 'relvm', fv, score_row, wts_row, err, mu, fl)
}

