# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp Example
#'
#' This is an example
#'
#' @export
timesTwo <- function(x) {
    .Call('relvm_timesTwo', PACKAGE = 'relvm', x)
}

#' Rcpp Example
#'
#' This is an example
#'
#' @export
dnorm_cpp <- function(x, mean = 0, sd = 1) {
    .Call('relvm_dnorm_cpp', PACKAGE = 'relvm', x, mean, sd)
}

